[build]
  command = "bun install --no-save && bun run build --cwd packages/app"
  publish = "packages/app/dist"
  functions = "netlify/functions"
  environment = { BUN_SKIP_INSTALL_SCRIPTS = "1" }

[dev]
  command = "bun run dev --cwd packages/app"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "bun install --no-save && bun run build --cwd packages/app"
  environment = { BUN_SKIP_INSTALL_SCRIPTS = "1" }

[context.deploy-preview]
  command = "bun install --no-save && bun run build --cwd packages/app"
  environment = { BUN_SKIP_INSTALL_SCRIPTS = "1" }

[context.branch-deploy]
  command = "bun install --no-save && bun run build --cwd packages/app"
  environment = { BUN_SKIP_INSTALL_SCRIPTS = "1" }
